version: '3.8'
services:
  postgres-lab-2:
    container_name: postgres-lab-2
    image: postgres:16
    environment:
      POSTGRES_DB: lab2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
